### PR TITLE
fix(login): render Agency Pass outside login form

### LINKED ISSUE #8: Logout deletes managed-user meta, breaking re-login via Agency Pass
## Summary

When a managed Agency Pass user logs out, `maybe_revoke_on_logout()` calls `$user->set_role('')`. This triggers the `set_user_role` hook, which fires `UserProfile::handle_role_change()`. That method sees the new role is not `agency_pass_admin` and deletes both `_agency_pass_user` and `_agency_pass_expires` meta.

Without the marker meta, the user is no longer recognized as managed. On the next magic-link request, `RequestHandler::handle_request()` treats them as a regular WordPress user and sends the "you already have an account — log in or reset your password" email instead of a magic link.

The same chain fires when `UserManager::revoke_role()` is called during cron-based expiry cleanup.

## Steps to reproduce

1. Configure `AGENCY_PASS_EMAIL_PATTERN`
2. Request a magic link and log in
3. Log out
4. Request a new magic link with the same email
5. Receive "you already have an account" email instead of a magic link

## Expected behavior

Managed users should be able to re-request a magic link after logging out.

## Root cause

`UserProfile::handle_role_change()` does not distinguish between a deliberate role change by an admin (→ promote to regular account) and a role revocation to `''` by Agency Pass itself (logout / expiry). Both paths delete the meta.

## Fix

Skip meta deletion when the new role is empty (`''`), since that represents an Agency Pass revocation, not a promotion.

### LINKED ISSUE #9: Expired managed users cannot re-request magic link
## Summary

When a managed user's TTL expires and they request a new magic link, the token is generated and sent. However, clicking the link fails because `UserManager::find_existing()` returns `null` for expired users, and `UserManager::create()` then fails — `wp_insert_user()` rejects the duplicate email address that still exists in the database.

## Steps to reproduce

1. Configure `AGENCY_PASS_EMAIL_PATTERN` with a short `AGENCY_PASS_USER_TTL`
2. Request a magic link and log in
3. Wait for the TTL to expire
4. Request a new magic link
5. Click the link → "Could not create emergency user" error

## Expected behavior

Expired managed users should be reactivated when clicking a new magic link, not recreated.

## Root cause

`UserManager::find_existing()` revokes the role of expired users and returns `null`. The caller `create_or_reuse()` then falls through to `create()`, which calls `wp_insert_user()` with the same email — WordPress rejects duplicate emails.

## Fix

`find_existing()` should return expired managed users so `extend()` can reactivate them (restore role + reset TTL) instead of attempting to create a new user.

### LINKED ISSUE #10: Block password reset for managed Agency Pass users
## Summary

Managed Agency Pass users have a random 64-character password and a temporary restricted role. The WordPress "Lost Password" flow is useless for them — resetting the password and logging in results in an account with no role and no access.

## Expected behavior

WordPress should reject password reset requests for managed users with a clear message ("Password reset is not allowed for this user").

## Implementation

Filter `allow_password_reset` to return `false` when the user has `_agency_pass_user` meta set to `'1'`.

### LINKED ISSUE #11: Add admin notice and role change confirmation on managed user profiles
## Summary

When editing a managed Agency Pass user's profile, there is no visible indication that the account is managed or that changing the role has permanent consequences (removes Agency Pass management).

## Expected behavior

1. **Admin notice**: A warning banner at the top of the user-edit page for managed users, stating that the account is managed by Agency Pass and that changing the role will permanently remove management.

2. **Role change confirmation**: When the role dropdown is changed, a JS `confirm()` dialog asks for explicit acknowledgement. Accept injects a hidden input that triggers meta deletion on save. Cancel reverts the dropdown to its original value.

This prevents accidental promotion of managed users to regular accounts.

## Implementation

- `admin_notices` hook for the warning banner (only on `user-edit` screen)
- `admin_footer` hook for the JS confirm dialog on the `#role` select
- `edit_user_profile_update` hook for processing the hidden input with nonce verification
- Nonce field rendered inside the existing managed-status section

### PR DESCRIPTION
**Pull request by apermo**
## Summary

- Move Agency Pass UI from `login_form` hook (fires inside the `<form>`) to `login_footer` (fires after it)
- Use JS to position the wrapper after `#loginform` for visual placement
- Style as a standalone card matching the WP login box appearance
- Fixes nested `<form>` causing admin login to fail
- Fix: preserve managed-user meta on logout/expiry role revocation (Closes #8)
- Fix: reactivate expired managed users instead of failing on duplicate email (Closes #9)
- Fix: block password reset for managed Agency Pass users (Closes #10)
- Feat: admin notice and JS confirm dialog on role change for managed user profiles (Closes #11)

## Test plan

- [x] Unit tests pass (51/51)
- [x] PHPStan level 6 passes
- [x] PHPCS passes (0 errors)
- [x] Playwright E2E tests pass

### CODE REVIEW

File: src/AdminNotice.php [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+	 * Show a warning when no audit trail plugin is active.
+	 *
+	 * @return void
+	 */
+	public static function missing_audit_logger(): void {
+		if ( ! current_user_can( 'manage_options' ) ) {
+			return;
+		}
+
+		?>
```
Comment (apermo) [inline src/AdminNotice.php]: consider using https://developer.wordpress.org/reference/functions/wp_admin_notice/

File: src/AuditLog.php [hunk 2]
```diff
@@ -5,33 +5,67 @@
...
+
+		// Fallback: always log to error_log().
+		add_action( 'agency_pass_link_requested', [ self::class, 'fallback_link_requested' ], 99, 3 );
+		add_action( 'agency_pass_login', [ self::class, 'fallback_login' ], 99, 3 );
+		add_action( 'agency_pass_user_cleanup', [ self::class, 'fallback_user_cleanup' ], 99, 1 );
 	}
 
 	/**
-	 * Log a magic link request.
+	 * Fallback: log magic link request to error_log.
```
Comment (apermo) [inline src/AuditLog.php]: Does not match Coding standards, should be: (The function) Does...

So "Logs magic link request to error_log as Fallback"

File: src/AuditLog.php [hunk 3]
```diff
@@ -64,13 +98,13 @@ public static function on_login( string $email, string $username, string $ip ):
 	}
 
 	/**
-	 * Log user cleanup.
+	 * Fallback: log user cleanup to error_log.
```
Comment (apermo) [inline src/AuditLog.php]: same

File: src/AuditLoggerInterface.php [hunk 4]
```diff
@@ -0,0 +1,28 @@
...
+/**
+ * Interface for audit trail logger implementations.
+ *
+ * Implementations bridge Agency Pass events to external audit trail plugins.
+ * Each implementation must check its backing plugin's availability at runtime.
+ */
+interface AuditLoggerInterface {
+
+	/**
+	 * Check whether the backing audit trail plugin is installed and active.
```
Comment (apermo) [inline src/AuditLoggerInterface.php]:
```suggestion
	 * Checks whether the backing audit trail plugin is installed and active.
```

Check all phpdocs for format, full project.

File: src/LoginForm.php [hunk 5]
```diff
@@ -49,31 +50,66 @@ public static function render(): void {
...
-	 * Show a confirmation message after a magic link request.
+	 * Show a result message after a magic link request.
 	 *
 	 * @param string $message The existing login message.
 	 *
 	 * @return string
 	 */
 	public static function confirmation_message( string $message ): string {
-		if ( ! isset( $_GET['agency_pass_sent'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
+		if ( ! isset( $_GET['agency_pass'] ) ) { // phpcs:ignore WordPress.Security.NonceVerification.Recommended
```
Comment (apermo) [inline src/LoginForm.php]: needs reason why ignored

File: src/LoginForm.php [hunk 6]
```diff
@@ -49,31 +50,66 @@ public static function render(): void {
...
 			return $message;
 		}
 
+		$result = sanitize_text_field( wp_unslash( $_GET['agency_pass'] ) ); // phpcs:ignore WordPress.Security.NonceVerification.Recommended
```
Comment (apermo) [inline src/LoginForm.php]: same

File: src/LoginForm.php [hunk 7]
```diff
@@ -49,31 +50,66 @@ public static function render(): void {
...
 
+	/**
+	 * Trigger the login form shake animation on rejection.
+	 *
+	 * Mirrors the wp_shake_js() behavior from WordPress core.
+	 *
+	 * @return void
+	 */
+	public static function maybe_shake(): void {
+		if ( // phpcs:ignore WordPress.Security.NonceVerification.Recommended
```
Comment (apermo) [inline src/LoginForm.php]: same, check all phpcs ignore if having a reason, that should actually be caught by phpstan?

File: src/RequestHandler.php [hunk 8]
```diff
@@ -47,12 +51,38 @@ public static function handle_request(): void {
 		do_action( 'agency_pass_link_requested', $email, $ip, $matched ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
 
 		if ( $matched ) {
+			// If a non-managed user with this email already exists, send them
+			// a "you have an account" email instead of a magic link.
```
Comment (apermo) [inline src/RequestHandler.php]: two line comment should be using /* */

File: src/RequestHandler.php [hunk 9]
```diff
@@ -47,12 +51,38 @@ public static function handle_request(): void {
 		do_action( 'agency_pass_link_requested', $email, $ip, $matched ); // phpcs:ignore WordPress.NamingConventions.PrefixAllGlobals.NonPrefixedHooknameFound
 
 		if ( $matched ) {
```
Comment (apermo) [inline src/RequestHandler.php:54]: weak condition

File: src/Role.php [hunk 10]
```diff
@@ -38,7 +75,7 @@ public static function register(): void {
 
 		add_role(
 			self::ROLE_NAME,
-			__( 'Agency Pass Admin', 'agency-pass' ),
+			'Agency Pass Admin',
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Role.php]: agreed with copilot

File: src/UserProfile.php [hunk 11]
```diff
@@ -0,0 +1,288 @@
...
+	 * Render the Agency Pass status section on a user's profile.
+	 *
+	 * @param WP_User $user The user being edited.
+	 *
+	 * @return void
+	 */
+	public static function render_status( WP_User $user ): void {
+		$is_managed = (bool) get_user_meta( $user->ID, '_agency_pass_user', true );
+
+		if ( $is_managed ) {
```
Comment (apermo) [inline src/UserProfile.php:40]: nit: technically ok, but i would still likely opt for === true for good measure

File: src/Plugin.php [hunk 12]
```diff
@@ -78,9 +78,17 @@ public static function boot(): void {
...
+
+		if ( ! AuditLog::has_available_logger() ) {
+			AdminNotice::register_hooks();
+			return;
+		}
+
+		AuditLog::register_hooks();
 		LoginForm::register_hooks();
 		RequestHandler::register_hooks();
 		Cleanup::register_hooks();
```
[the remark this answers is not in the document]
Comment (apermo) [reply src/Plugin.php:92]: Intentional security requirement. Emergency login without audit trail is a liability. Documented in README and CHANGELOG.

File: uninstall.php [hunk 13]
```diff
@@ -9,4 +9,4 @@
 require_once __DIR__ . '/vendor/autoload.php';
 
 Role::unregister();
-UserManager::delete_all();
+UserManager::revoke_all();
```
[the remark this answers is not in the document]
Comment (apermo) [reply uninstall.php:12]: Intentional — prevents content orphaning. Full uninstall UI with keep/delete choice tracked in #6.

File: .github/workflows/e2e.yml [hunk 14]
```diff
@@ -10,6 +10,7 @@ permissions:
 
 jobs:
     e2e:
-        uses: apermo/reusable-workflows/.github/workflows/reusable-wp-e2e.yml@main
+        uses: apermo/reusable-workflows/.github/workflows/reusable-wp-e2e.yml@feature/wp-env-e2e
```
[the remark this answers is not in the document]
Comment (apermo) [reply .github/workflows/e2e.yml]: Temporary — will change to @main once apermo/reusable-workflows#15 is merged.

File: phpcs.xml.dist [hunk 15]
```diff
@@ -8,8 +8,10 @@
     <file>.</file>
     <exclude-pattern>vendor/*</exclude-pattern>
     <exclude-pattern>node_modules/*</exclude-pattern>
+    <exclude-pattern>.ddev/*</exclude-pattern>
 
     <arg name="extensions" value="php"/>
+    <config name="ignore_warnings_on_exit" value="1"/>
```
[the remark this answers is not in the document]
Comment (apermo) [reply phpcs.xml.dist:14]: Intentional — remaining warnings are short variable names ($ip, $ttl) pending upstream fix in apermo/apermo-coding-standards#92. Errors still fail CI.
